# Generated by Django 5.0.1 on 2024-01-23 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="performance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="theatre.performance",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="reservation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="theatre.reservation",
            ),
        ),
    ]
